name: 'Gadget deploy'
description: 'Deploy user scripts or gadgets to Wikimedia sites'
author: 'Siddharth VP'
inputs:
  apiUrl:
    required: true
    description: 'API URL of the wiki, eg. https://en.wikipedia.org/w/api.php'
  username:
    description: 'Username for use with BotPassword authentication'
  password:
    description: 'Password for use with BotPassword authentication'
  oauth2Token:
    description: 'Access token for use with OAuth2 authentication'
  paths:
    description: 'Paths to sync with wiki pages. Can be multiple lines. Each line should be path-to-file-in-repo <space> wiki-page-title. Note the local file path must not contain spaces.'
  editSummary:
    description: 'Edit summary to use while updating pages'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: arrow-up-right
  color: green
